### ISSUE TITLE
Use gi instead of pygtk

### ISSUE THREAD

**Issue by eisensheng** [captn3m0/hackertray#10]
It's the preferred method to write Gtk applications in python.  The new music player for gnome gnome-music (incredible creative name!) also uses gi.  It's also portable to [pypy](https://pypi.python.org/pypi/pgi/0.0.6.2).

https://python-gtk-3-tutorial.readthedocs.org/en/latest/index.html

**Comment by captn3m0** [comment]
Just released a new version with Python 3 and gi support (and a few more features): 

Turns out the segfault was an [issue with gi](https://bugzilla.gnome.org/show_bug.cgi?id=709183).
