### ISSUE TITLE
Feature: configurable positon of controls.

### ISSUE THREAD

**Issue by Gonzih** [captn3m0/hackertray#13]
Hi, I tried it out and it works very well. Almost perfectly. One thing that I don't like is that if my tray is on the bottom I can by mistake click on the "Quit" in menu (it happens often actually). Can you provide some configuration for example in `.config/hackertray` directory? I would love to be able to set some option that will force control buttons will be displayed on top of the menu.

Thanks! And I love simplicity of project idea.

**Comment by captn3m0** [comment]
Added a `--reverse` option in 4.0.1 release today :tada:
