### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by palnabarun** [captn3m0/hackertray#27]
I tried installing it on Python 3.5.2 via Pip 9.0.1
While starting, it threw a SyntaxError for missing paranthesis.

**Comment by captn3m0** [comment]
I haven't been actively working on this since I've shifted to Arch+i3bar as my setup, which doesn't support libappindicator (which is what hackertray uses).

**Comment by captn3m0** [comment]
Just released a new version with Python 3 support (and a few more features).
